[project]
name = 'Decentralized-Freelance-Marketplace'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.milestone-tracking]
path = 'contracts/milestone-tracking.clar'
clarity_version = 2
epoch = 2.5

[contracts.project-escrow]
path = 'contracts/project-escrow.clar'
clarity_version = 2
epoch = 2.5

[contracts.skill-verification]
path = 'contracts/skill-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
